/* tslint:disable */
/* eslint-disable */
/**
 * Menzili Backend API
 * REST API for Menzili platform with OTP authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthFillNamePost200Response,
  AuthFillNamePostRequest,
  AuthLoginPost200Response,
  AuthLoginPostRequest,
  AuthValidOtpPost200Response,
  AuthValidOtpPostRequest,
} from '../models/index';
import {
    AuthFillNamePost200ResponseFromJSON,
    AuthFillNamePost200ResponseToJSON,
    AuthFillNamePostRequestFromJSON,
    AuthFillNamePostRequestToJSON,
    AuthLoginPost200ResponseFromJSON,
    AuthLoginPost200ResponseToJSON,
    AuthLoginPostRequestFromJSON,
    AuthLoginPostRequestToJSON,
    AuthValidOtpPost200ResponseFromJSON,
    AuthValidOtpPost200ResponseToJSON,
    AuthValidOtpPostRequestFromJSON,
    AuthValidOtpPostRequestToJSON,
} from '../models/index';

export interface AuthFillNamePostOperationRequest {
    accept: string;
    acceptLanguage: AuthFillNamePostOperationAcceptLanguageEnum;
    authorization: string;
    authFillNamePostRequest: AuthFillNamePostRequest;
}

export interface AuthLoginPostOperationRequest {
    accept: string;
    acceptLanguage: AuthLoginPostOperationAcceptLanguageEnum;
    authLoginPostRequest: AuthLoginPostRequest;
}

export interface AuthValidOtpPostOperationRequest {
    accept: string;
    acceptLanguage: AuthValidOtpPostOperationAcceptLanguageEnum;
    authValidOtpPostRequest: AuthValidOtpPostRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for authFillNamePost without sending the request
     */
    async authFillNamePostRequestOpts(requestParameters: AuthFillNamePostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accept'] == null) {
            throw new runtime.RequiredError(
                'accept',
                'Required parameter "accept" was null or undefined when calling authFillNamePost().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling authFillNamePost().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling authFillNamePost().'
            );
        }

        if (requestParameters['authFillNamePostRequest'] == null) {
            throw new runtime.RequiredError(
                'authFillNamePostRequest',
                'Required parameter "authFillNamePostRequest" was null or undefined when calling authFillNamePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['Accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/fill-name`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthFillNamePostRequestToJSON(requestParameters['authFillNamePostRequest']),
        };
    }

    /**
     * Update user name after OTP verification. Requires authentication token.
     * Complete user profile (fill name)
     */
    async authFillNamePostRaw(requestParameters: AuthFillNamePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthFillNamePost200Response>> {
        const requestOptions = await this.authFillNamePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthFillNamePost200ResponseFromJSON(jsonValue));
    }

    /**
     * Update user name after OTP verification. Requires authentication token.
     * Complete user profile (fill name)
     */
    async authFillNamePost(requestParameters: AuthFillNamePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthFillNamePost200Response> {
        const response = await this.authFillNamePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authLoginPost without sending the request
     */
    async authLoginPostRequestOpts(requestParameters: AuthLoginPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accept'] == null) {
            throw new runtime.RequiredError(
                'accept',
                'Required parameter "accept" was null or undefined when calling authLoginPost().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling authLoginPost().'
            );
        }

        if (requestParameters['authLoginPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authLoginPostRequest',
                'Required parameter "authLoginPostRequest" was null or undefined when calling authLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['Accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }


        let urlPath = `/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthLoginPostRequestToJSON(requestParameters['authLoginPostRequest']),
        };
    }

    /**
     * Send OTP via WhatsApp to user\'s phone number
     * Request OTP for login
     */
    async authLoginPostRaw(requestParameters: AuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLoginPost200Response>> {
        const requestOptions = await this.authLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLoginPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Send OTP via WhatsApp to user\'s phone number
     * Request OTP for login
     */
    async authLoginPost(requestParameters: AuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLoginPost200Response> {
        const response = await this.authLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authValidOtpPost without sending the request
     */
    async authValidOtpPostRequestOpts(requestParameters: AuthValidOtpPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accept'] == null) {
            throw new runtime.RequiredError(
                'accept',
                'Required parameter "accept" was null or undefined when calling authValidOtpPost().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling authValidOtpPost().'
            );
        }

        if (requestParameters['authValidOtpPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authValidOtpPostRequest',
                'Required parameter "authValidOtpPostRequest" was null or undefined when calling authValidOtpPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['Accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }


        let urlPath = `/auth/valid-otp`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthValidOtpPostRequestToJSON(requestParameters['authValidOtpPostRequest']),
        };
    }

    /**
     * Verify OTP code and get authentication token
     * Verify OTP
     */
    async authValidOtpPostRaw(requestParameters: AuthValidOtpPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthValidOtpPost200Response>> {
        const requestOptions = await this.authValidOtpPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthValidOtpPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Verify OTP code and get authentication token
     * Verify OTP
     */
    async authValidOtpPost(requestParameters: AuthValidOtpPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthValidOtpPost200Response> {
        const response = await this.authValidOtpPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AuthFillNamePostOperationAcceptLanguageEnum = {
    Ar: 'ar',
    Fr: 'fr',
    En: 'en'
} as const;
export type AuthFillNamePostOperationAcceptLanguageEnum = typeof AuthFillNamePostOperationAcceptLanguageEnum[keyof typeof AuthFillNamePostOperationAcceptLanguageEnum];
/**
 * @export
 */
export const AuthLoginPostOperationAcceptLanguageEnum = {
    Ar: 'ar',
    Fr: 'fr',
    En: 'en'
} as const;
export type AuthLoginPostOperationAcceptLanguageEnum = typeof AuthLoginPostOperationAcceptLanguageEnum[keyof typeof AuthLoginPostOperationAcceptLanguageEnum];
/**
 * @export
 */
export const AuthValidOtpPostOperationAcceptLanguageEnum = {
    Ar: 'ar',
    Fr: 'fr',
    En: 'en'
} as const;
export type AuthValidOtpPostOperationAcceptLanguageEnum = typeof AuthValidOtpPostOperationAcceptLanguageEnum[keyof typeof AuthValidOtpPostOperationAcceptLanguageEnum];
