/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  InlineObject1,
  ListingsUpdatePost200Response,
  ListingsUpdatePostRequest,
  TypeResource,
  User,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    ListingsUpdatePost200ResponseFromJSON,
    ListingsUpdatePost200ResponseToJSON,
    ListingsUpdatePostRequestFromJSON,
    ListingsUpdatePostRequestToJSON,
    TypeResourceFromJSON,
    TypeResourceToJSON,
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface ListingsUpdatePostOperationRequest {
    listingsUpdatePostRequest: ListingsUpdatePostRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for getDataGet without sending the request
     */
    async getDataGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/get_data`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getDataGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TypeResource>>> {
        const requestOptions = await this.getDataGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TypeResourceFromJSON));
    }

    /**
     */
    async getDataGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TypeResource>> {
        const response = await this.getDataGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listingsUpdatePost without sending the request
     */
    async listingsUpdatePostRequestOpts(requestParameters: ListingsUpdatePostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listingsUpdatePostRequest'] == null) {
            throw new runtime.RequiredError(
                'listingsUpdatePostRequest',
                'Required parameter "listingsUpdatePostRequest" was null or undefined when calling listingsUpdatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/listings/update`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListingsUpdatePostRequestToJSON(requestParameters['listingsUpdatePostRequest']),
        };
    }

    /**
     */
    async listingsUpdatePostRaw(requestParameters: ListingsUpdatePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListingsUpdatePost200Response>> {
        const requestOptions = await this.listingsUpdatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListingsUpdatePost200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async listingsUpdatePost(requestParameters: ListingsUpdatePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListingsUpdatePost200Response> {
        const response = await this.listingsUpdatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for userGet without sending the request
     */
    async userGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/user`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async userGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.userGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     */
    async userGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.userGetRaw(initOverrides);
        return await response.value();
    }

}
