/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DetailsCities200Response,
  DetailsIndex200Response,
  DetailsWilayas200Response,
  InlineObject1,
} from '../models/index';
import {
    DetailsCities200ResponseFromJSON,
    DetailsCities200ResponseToJSON,
    DetailsIndex200ResponseFromJSON,
    DetailsIndex200ResponseToJSON,
    DetailsWilayas200ResponseFromJSON,
    DetailsWilayas200ResponseToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
} from '../models/index';

export interface DetailsCitiesRequest {
    wilayaId: number;
}

/**
 * 
 */
export class DetailsApi extends runtime.BaseAPI {

    /**
     * Creates request options for detailsCities without sending the request
     */
    async detailsCitiesRequestOpts(requestParameters: DetailsCitiesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['wilayaId'] == null) {
            throw new runtime.RequiredError(
                'wilayaId',
                'Required parameter "wilayaId" was null or undefined when calling detailsCities().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['wilayaId'] != null) {
            queryParameters['wilaya_id'] = requestParameters['wilayaId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/listings/cities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async detailsCitiesRaw(requestParameters: DetailsCitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailsCities200Response>> {
        const requestOptions = await this.detailsCitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailsCities200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async detailsCities(requestParameters: DetailsCitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailsCities200Response> {
        const response = await this.detailsCitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for detailsIndex without sending the request
     */
    async detailsIndexRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/listings/details`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async detailsIndexRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailsIndex200Response>> {
        const requestOptions = await this.detailsIndexRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async detailsIndex(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailsIndex200Response> {
        const response = await this.detailsIndexRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for detailsWilayas without sending the request
     */
    async detailsWilayasRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/listings/wilayas`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async detailsWilayasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailsWilayas200Response>> {
        const requestOptions = await this.detailsWilayasRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailsWilayas200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async detailsWilayas(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailsWilayas200Response> {
        const response = await this.detailsWilayasRaw(initOverrides);
        return await response.value();
    }

}
