/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  InlineObject1,
  ListingsDestroy200Response,
  ListingsIndex200Response,
  ListingsStore201Response,
  StoreRequest,
  UpdateRequest,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    ListingsDestroy200ResponseFromJSON,
    ListingsDestroy200ResponseToJSON,
    ListingsIndex200ResponseFromJSON,
    ListingsIndex200ResponseToJSON,
    ListingsStore201ResponseFromJSON,
    ListingsStore201ResponseToJSON,
    StoreRequestFromJSON,
    StoreRequestToJSON,
    UpdateRequestFromJSON,
    UpdateRequestToJSON,
} from '../models/index';

export interface ListingsDestroyRequest {
    listing: number;
}

export interface ListingsIndexRequest {
    perPage?: string;
}

export interface ListingsStoreRequest {
    storeRequest: StoreRequest;
}

export interface ListingsUpdateRequest {
    listing: number;
    updateRequest?: UpdateRequest;
}

/**
 * 
 */
export class ListingApi extends runtime.BaseAPI {

    /**
     * Creates request options for listingsDestroy without sending the request
     */
    async listingsDestroyRequestOpts(requestParameters: ListingsDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listing'] == null) {
            throw new runtime.RequiredError(
                'listing',
                'Required parameter "listing" was null or undefined when calling listingsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/listings/{listing}`;
        urlPath = urlPath.replace(`{${"listing"}}`, encodeURIComponent(String(requestParameters['listing'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listingsDestroyRaw(requestParameters: ListingsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListingsDestroy200Response>> {
        const requestOptions = await this.listingsDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListingsDestroy200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async listingsDestroy(requestParameters: ListingsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListingsDestroy200Response> {
        const response = await this.listingsDestroyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listingsIndex without sending the request
     */
    async listingsIndexRequestOpts(requestParameters: ListingsIndexRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/listings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listingsIndexRaw(requestParameters: ListingsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListingsIndex200Response>> {
        const requestOptions = await this.listingsIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListingsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async listingsIndex(requestParameters: ListingsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListingsIndex200Response> {
        const response = await this.listingsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listingsStore without sending the request
     */
    async listingsStoreRequestOpts(requestParameters: ListingsStoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['storeRequest'] == null) {
            throw new runtime.RequiredError(
                'storeRequest',
                'Required parameter "storeRequest" was null or undefined when calling listingsStore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/listings`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoreRequestToJSON(requestParameters['storeRequest']),
        };
    }

    /**
     */
    async listingsStoreRaw(requestParameters: ListingsStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListingsStore201Response>> {
        const requestOptions = await this.listingsStoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListingsStore201ResponseFromJSON(jsonValue));
    }

    /**
     */
    async listingsStore(requestParameters: ListingsStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListingsStore201Response> {
        const response = await this.listingsStoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listingsUpdate without sending the request
     */
    async listingsUpdateRequestOpts(requestParameters: ListingsUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listing'] == null) {
            throw new runtime.RequiredError(
                'listing',
                'Required parameter "listing" was null or undefined when calling listingsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/listings/{listing}`;
        urlPath = urlPath.replace(`{${"listing"}}`, encodeURIComponent(String(requestParameters['listing'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRequestToJSON(requestParameters['updateRequest']),
        };
    }

    /**
     */
    async listingsUpdateRaw(requestParameters: ListingsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListingsStore201Response>> {
        const requestOptions = await this.listingsUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListingsStore201ResponseFromJSON(jsonValue));
    }

    /**
     */
    async listingsUpdate(requestParameters: ListingsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListingsStore201Response> {
        const response = await this.listingsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
