/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRequestOtpRequest
 */
export interface AuthRequestOtpRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthRequestOtpRequest
     */
    phone: string;
}

/**
 * Check if a given object implements the AuthRequestOtpRequest interface.
 */
export function instanceOfAuthRequestOtpRequest(value: object): value is AuthRequestOtpRequest {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function AuthRequestOtpRequestFromJSON(json: any): AuthRequestOtpRequest {
    return AuthRequestOtpRequestFromJSONTyped(json, false);
}

export function AuthRequestOtpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRequestOtpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'],
    };
}

export function AuthRequestOtpRequestToJSON(json: any): AuthRequestOtpRequest {
    return AuthRequestOtpRequestToJSONTyped(json, false);
}

export function AuthRequestOtpRequestToJSONTyped(value?: AuthRequestOtpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
    };
}

