/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';

/**
 * 
 * @export
 * @interface AuthVerifyOtp404Response
 */
export interface AuthVerifyOtp404Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthVerifyOtp404Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof AuthVerifyOtp404Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
    /**
     * 
     * @type {AuthVerifyOtp404ResponseStatusEnum}
     * @memberof AuthVerifyOtp404Response
     */
    status: AuthVerifyOtp404ResponseStatusEnum;
}


/**
 * @export
 */
export const AuthVerifyOtp404ResponseStatusEnum = {
    NUMBER_404: 404
} as const;
export type AuthVerifyOtp404ResponseStatusEnum = typeof AuthVerifyOtp404ResponseStatusEnum[keyof typeof AuthVerifyOtp404ResponseStatusEnum];


/**
 * Check if a given object implements the AuthVerifyOtp404Response interface.
 */
export function instanceOfAuthVerifyOtp404Response(value: object): value is AuthVerifyOtp404Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AuthVerifyOtp404ResponseFromJSON(json: any): AuthVerifyOtp404Response {
    return AuthVerifyOtp404ResponseFromJSONTyped(json, false);
}

export function AuthVerifyOtp404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthVerifyOtp404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
        'status': json['status'],
    };
}

export function AuthVerifyOtp404ResponseToJSON(json: any): AuthVerifyOtp404Response {
    return AuthVerifyOtp404ResponseToJSONTyped(json, false);
}

export function AuthVerifyOtp404ResponseToJSONTyped(value?: AuthVerifyOtp404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
        'status': value['status'],
    };
}

