/* tslint:disable */
/* eslint-disable */
/**
 * Menzili Backend API
 * REST API for Menzili platform with OTP authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthFillNamePost200ResponseData
 */
export interface AuthFillNamePost200ResponseData {
    /**
     * User resource object
     * @type {object}
     * @memberof AuthFillNamePost200ResponseData
     */
    user?: object;
}

/**
 * Check if a given object implements the AuthFillNamePost200ResponseData interface.
 */
export function instanceOfAuthFillNamePost200ResponseData(value: object): value is AuthFillNamePost200ResponseData {
    return true;
}

export function AuthFillNamePost200ResponseDataFromJSON(json: any): AuthFillNamePost200ResponseData {
    return AuthFillNamePost200ResponseDataFromJSONTyped(json, false);
}

export function AuthFillNamePost200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthFillNamePost200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function AuthFillNamePost200ResponseDataToJSON(json: any): AuthFillNamePost200ResponseData {
    return AuthFillNamePost200ResponseDataToJSONTyped(json, false);
}

export function AuthFillNamePost200ResponseDataToJSONTyped(value?: AuthFillNamePost200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': value['user'],
    };
}

