/* tslint:disable */
/* eslint-disable */
/**
 * Menzili Backend API
 * REST API for Menzili platform with OTP authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthFillNamePostRequest
 */
export interface AuthFillNamePostRequest {
    /**
     * User's full name (2-100 characters)
     * @type {string}
     * @memberof AuthFillNamePostRequest
     */
    name: string;
}

/**
 * Check if a given object implements the AuthFillNamePostRequest interface.
 */
export function instanceOfAuthFillNamePostRequest(value: object): value is AuthFillNamePostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AuthFillNamePostRequestFromJSON(json: any): AuthFillNamePostRequest {
    return AuthFillNamePostRequestFromJSONTyped(json, false);
}

export function AuthFillNamePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthFillNamePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function AuthFillNamePostRequestToJSON(json: any): AuthFillNamePostRequest {
    return AuthFillNamePostRequestToJSONTyped(json, false);
}

export function AuthFillNamePostRequestToJSONTyped(value?: AuthFillNamePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

