/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthVerifyOtpRequest
 */
export interface AuthVerifyOtpRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthVerifyOtpRequest
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof AuthVerifyOtpRequest
     */
    otpCode: string;
}

/**
 * Check if a given object implements the AuthVerifyOtpRequest interface.
 */
export function instanceOfAuthVerifyOtpRequest(value: object): value is AuthVerifyOtpRequest {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('otpCode' in value) || value['otpCode'] === undefined) return false;
    return true;
}

export function AuthVerifyOtpRequestFromJSON(json: any): AuthVerifyOtpRequest {
    return AuthVerifyOtpRequestFromJSONTyped(json, false);
}

export function AuthVerifyOtpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthVerifyOtpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'],
        'otpCode': json['otp_code'],
    };
}

export function AuthVerifyOtpRequestToJSON(json: any): AuthVerifyOtpRequest {
    return AuthVerifyOtpRequestToJSONTyped(json, false);
}

export function AuthVerifyOtpRequestToJSONTyped(value?: AuthVerifyOtpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
        'otp_code': value['otpCode'],
    };
}

