/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';
import type { AuthCompleteProfile200ResponseData } from './AuthCompleteProfile200ResponseData';
import {
    AuthCompleteProfile200ResponseDataFromJSON,
    AuthCompleteProfile200ResponseDataFromJSONTyped,
    AuthCompleteProfile200ResponseDataToJSON,
    AuthCompleteProfile200ResponseDataToJSONTyped,
} from './AuthCompleteProfile200ResponseData';

/**
 * 
 * @export
 * @interface AuthCompleteProfile200Response
 */
export interface AuthCompleteProfile200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthCompleteProfile200Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof AuthCompleteProfile200Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
    /**
     * 
     * @type {AuthCompleteProfile200ResponseStatusEnum}
     * @memberof AuthCompleteProfile200Response
     */
    status: AuthCompleteProfile200ResponseStatusEnum;
    /**
     * 
     * @type {AuthCompleteProfile200ResponseData}
     * @memberof AuthCompleteProfile200Response
     */
    data: AuthCompleteProfile200ResponseData;
}


/**
 * @export
 */
export const AuthCompleteProfile200ResponseStatusEnum = {
    NUMBER_200: 200
} as const;
export type AuthCompleteProfile200ResponseStatusEnum = typeof AuthCompleteProfile200ResponseStatusEnum[keyof typeof AuthCompleteProfile200ResponseStatusEnum];


/**
 * Check if a given object implements the AuthCompleteProfile200Response interface.
 */
export function instanceOfAuthCompleteProfile200Response(value: object): value is AuthCompleteProfile200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AuthCompleteProfile200ResponseFromJSON(json: any): AuthCompleteProfile200Response {
    return AuthCompleteProfile200ResponseFromJSONTyped(json, false);
}

export function AuthCompleteProfile200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthCompleteProfile200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
        'status': json['status'],
        'data': AuthCompleteProfile200ResponseDataFromJSON(json['data']),
    };
}

export function AuthCompleteProfile200ResponseToJSON(json: any): AuthCompleteProfile200Response {
    return AuthCompleteProfile200ResponseToJSONTyped(json, false);
}

export function AuthCompleteProfile200ResponseToJSONTyped(value?: AuthCompleteProfile200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
        'status': value['status'],
        'data': AuthCompleteProfile200ResponseDataToJSON(value['data']),
    };
}

