/* tslint:disable */
/* eslint-disable */
/**
 * Menzili Backend API
 * REST API for Menzili platform with OTP authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthLoginPost200ResponseData } from './AuthLoginPost200ResponseData';
import {
    AuthLoginPost200ResponseDataFromJSON,
    AuthLoginPost200ResponseDataFromJSONTyped,
    AuthLoginPost200ResponseDataToJSON,
    AuthLoginPost200ResponseDataToJSONTyped,
} from './AuthLoginPost200ResponseData';

/**
 * 
 * @export
 * @interface AuthLoginPost200Response
 */
export interface AuthLoginPost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthLoginPost200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthLoginPost200Response
     */
    status?: number;
    /**
     * 
     * @type {AuthLoginPost200ResponseData}
     * @memberof AuthLoginPost200Response
     */
    data?: AuthLoginPost200ResponseData;
}

/**
 * Check if a given object implements the AuthLoginPost200Response interface.
 */
export function instanceOfAuthLoginPost200Response(value: object): value is AuthLoginPost200Response {
    return true;
}

export function AuthLoginPost200ResponseFromJSON(json: any): AuthLoginPost200Response {
    return AuthLoginPost200ResponseFromJSONTyped(json, false);
}

export function AuthLoginPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : AuthLoginPost200ResponseDataFromJSON(json['data']),
    };
}

export function AuthLoginPost200ResponseToJSON(json: any): AuthLoginPost200Response {
    return AuthLoginPost200ResponseToJSONTyped(json, false);
}

export function AuthLoginPost200ResponseToJSONTyped(value?: AuthLoginPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'status': value['status'],
        'data': AuthLoginPost200ResponseDataToJSON(value['data']),
    };
}

