/* tslint:disable */
/* eslint-disable */
/**
 * Menzili Backend API
 * REST API for Menzili platform with OTP authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginPostRequest
 */
export interface AuthLoginPostRequest {
    /**
     * Phone number with country code
     * @type {string}
     * @memberof AuthLoginPostRequest
     */
    phone: string;
}

/**
 * Check if a given object implements the AuthLoginPostRequest interface.
 */
export function instanceOfAuthLoginPostRequest(value: object): value is AuthLoginPostRequest {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function AuthLoginPostRequestFromJSON(json: any): AuthLoginPostRequest {
    return AuthLoginPostRequestFromJSONTyped(json, false);
}

export function AuthLoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'],
    };
}

export function AuthLoginPostRequestToJSON(json: any): AuthLoginPostRequest {
    return AuthLoginPostRequestToJSONTyped(json, false);
}

export function AuthLoginPostRequestToJSONTyped(value?: AuthLoginPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
    };
}

