/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';

/**
 * 
 * @export
 * @interface AuthRequestOtp403Response
 */
export interface AuthRequestOtp403Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthRequestOtp403Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof AuthRequestOtp403Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
    /**
     * 
     * @type {AuthRequestOtp403ResponseStatusEnum}
     * @memberof AuthRequestOtp403Response
     */
    status: AuthRequestOtp403ResponseStatusEnum;
    /**
     * 
     * @type {Null}
     * @memberof AuthRequestOtp403Response
     */
    data: null;
}


/**
 * @export
 */
export const AuthRequestOtp403ResponseStatusEnum = {
    NUMBER_403: 403
} as const;
export type AuthRequestOtp403ResponseStatusEnum = typeof AuthRequestOtp403ResponseStatusEnum[keyof typeof AuthRequestOtp403ResponseStatusEnum];


/**
 * Check if a given object implements the AuthRequestOtp403Response interface.
 */
export function instanceOfAuthRequestOtp403Response(value: object): value is AuthRequestOtp403Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AuthRequestOtp403ResponseFromJSON(json: any): AuthRequestOtp403Response {
    return AuthRequestOtp403ResponseFromJSONTyped(json, false);
}

export function AuthRequestOtp403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRequestOtp403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
        'status': json['status'],
        'data': json['data'],
    };
}

export function AuthRequestOtp403ResponseToJSON(json: any): AuthRequestOtp403Response {
    return AuthRequestOtp403ResponseToJSONTyped(json, false);
}

export function AuthRequestOtp403ResponseToJSONTyped(value?: AuthRequestOtp403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
        'status': value['status'],
        'data': value['data'],
    };
}

