/* tslint:disable */
/* eslint-disable */
/**
 * Menzili Backend API
 * REST API for Menzili platform with OTP authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthValidOtpPost200ResponseData
 */
export interface AuthValidOtpPost200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof AuthValidOtpPost200ResponseData
     */
    token?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthValidOtpPost200ResponseData
     */
    fillName?: boolean;
}

/**
 * Check if a given object implements the AuthValidOtpPost200ResponseData interface.
 */
export function instanceOfAuthValidOtpPost200ResponseData(value: object): value is AuthValidOtpPost200ResponseData {
    return true;
}

export function AuthValidOtpPost200ResponseDataFromJSON(json: any): AuthValidOtpPost200ResponseData {
    return AuthValidOtpPost200ResponseDataFromJSONTyped(json, false);
}

export function AuthValidOtpPost200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthValidOtpPost200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'fillName': json['fill_name'] == null ? undefined : json['fill_name'],
    };
}

export function AuthValidOtpPost200ResponseDataToJSON(json: any): AuthValidOtpPost200ResponseData {
    return AuthValidOtpPost200ResponseDataToJSONTyped(json, false);
}

export function AuthValidOtpPost200ResponseDataToJSONTyped(value?: AuthValidOtpPost200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'fill_name': value['fillName'],
    };
}

