/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRequestOtp403ResponseMessage
 */
export interface AuthRequestOtp403ResponseMessage {
}

/**
 * Check if a given object implements the AuthRequestOtp403ResponseMessage interface.
 */
export function instanceOfAuthRequestOtp403ResponseMessage(value: object): value is AuthRequestOtp403ResponseMessage {
    return true;
}

export function AuthRequestOtp403ResponseMessageFromJSON(json: any): AuthRequestOtp403ResponseMessage {
    return AuthRequestOtp403ResponseMessageFromJSONTyped(json, false);
}

export function AuthRequestOtp403ResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRequestOtp403ResponseMessage {
    return json;
}

export function AuthRequestOtp403ResponseMessageToJSON(json: any): AuthRequestOtp403ResponseMessage {
    return AuthRequestOtp403ResponseMessageToJSONTyped(json, false);
}

export function AuthRequestOtp403ResponseMessageToJSONTyped(value?: AuthRequestOtp403ResponseMessage | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

