/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRequestOtp200ResponseData
 */
export interface AuthRequestOtp200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof AuthRequestOtp200ResponseData
     */
    otpCode: string;
}

/**
 * Check if a given object implements the AuthRequestOtp200ResponseData interface.
 */
export function instanceOfAuthRequestOtp200ResponseData(value: object): value is AuthRequestOtp200ResponseData {
    if (!('otpCode' in value) || value['otpCode'] === undefined) return false;
    return true;
}

export function AuthRequestOtp200ResponseDataFromJSON(json: any): AuthRequestOtp200ResponseData {
    return AuthRequestOtp200ResponseDataFromJSONTyped(json, false);
}

export function AuthRequestOtp200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRequestOtp200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'otpCode': json['otp_code'],
    };
}

export function AuthRequestOtp200ResponseDataToJSON(json: any): AuthRequestOtp200ResponseData {
    return AuthRequestOtp200ResponseDataToJSONTyped(json, false);
}

export function AuthRequestOtp200ResponseDataToJSONTyped(value?: AuthRequestOtp200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'otp_code': value['otpCode'],
    };
}

