/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResource } from './UserResource';
import {
    UserResourceFromJSON,
    UserResourceFromJSONTyped,
    UserResourceToJSON,
    UserResourceToJSONTyped,
} from './UserResource';

/**
 * 
 * @export
 * @interface AuthCompleteProfile200ResponseData
 */
export interface AuthCompleteProfile200ResponseData {
    /**
     * 
     * @type {UserResource}
     * @memberof AuthCompleteProfile200ResponseData
     */
    user: UserResource;
}

/**
 * Check if a given object implements the AuthCompleteProfile200ResponseData interface.
 */
export function instanceOfAuthCompleteProfile200ResponseData(value: object): value is AuthCompleteProfile200ResponseData {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function AuthCompleteProfile200ResponseDataFromJSON(json: any): AuthCompleteProfile200ResponseData {
    return AuthCompleteProfile200ResponseDataFromJSONTyped(json, false);
}

export function AuthCompleteProfile200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthCompleteProfile200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserResourceFromJSON(json['user']),
    };
}

export function AuthCompleteProfile200ResponseDataToJSON(json: any): AuthCompleteProfile200ResponseData {
    return AuthCompleteProfile200ResponseDataToJSONTyped(json, false);
}

export function AuthCompleteProfile200ResponseDataToJSONTyped(value?: AuthCompleteProfile200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserResourceToJSON(value['user']),
    };
}

