/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthCompleteProfileRequest
 */
export interface AuthCompleteProfileRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthCompleteProfileRequest
     */
    name: string;
}

/**
 * Check if a given object implements the AuthCompleteProfileRequest interface.
 */
export function instanceOfAuthCompleteProfileRequest(value: object): value is AuthCompleteProfileRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AuthCompleteProfileRequestFromJSON(json: any): AuthCompleteProfileRequest {
    return AuthCompleteProfileRequestFromJSONTyped(json, false);
}

export function AuthCompleteProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthCompleteProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function AuthCompleteProfileRequestToJSON(json: any): AuthCompleteProfileRequest {
    return AuthCompleteProfileRequestToJSONTyped(json, false);
}

export function AuthCompleteProfileRequestToJSONTyped(value?: AuthCompleteProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

