/* tslint:disable */
/* eslint-disable */
/**
 * Menzili Backend API
 * REST API for Menzili platform with OTP authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthFillNamePost200ResponseData } from './AuthFillNamePost200ResponseData';
import {
    AuthFillNamePost200ResponseDataFromJSON,
    AuthFillNamePost200ResponseDataFromJSONTyped,
    AuthFillNamePost200ResponseDataToJSON,
    AuthFillNamePost200ResponseDataToJSONTyped,
} from './AuthFillNamePost200ResponseData';

/**
 * 
 * @export
 * @interface AuthFillNamePost200Response
 */
export interface AuthFillNamePost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthFillNamePost200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthFillNamePost200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthFillNamePost200Response
     */
    status?: number;
    /**
     * 
     * @type {AuthFillNamePost200ResponseData}
     * @memberof AuthFillNamePost200Response
     */
    data?: AuthFillNamePost200ResponseData;
}

/**
 * Check if a given object implements the AuthFillNamePost200Response interface.
 */
export function instanceOfAuthFillNamePost200Response(value: object): value is AuthFillNamePost200Response {
    return true;
}

export function AuthFillNamePost200ResponseFromJSON(json: any): AuthFillNamePost200Response {
    return AuthFillNamePost200ResponseFromJSONTyped(json, false);
}

export function AuthFillNamePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthFillNamePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : AuthFillNamePost200ResponseDataFromJSON(json['data']),
    };
}

export function AuthFillNamePost200ResponseToJSON(json: any): AuthFillNamePost200Response {
    return AuthFillNamePost200ResponseToJSONTyped(json, false);
}

export function AuthFillNamePost200ResponseToJSONTyped(value?: AuthFillNamePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'status': value['status'],
        'data': AuthFillNamePost200ResponseDataToJSON(value['data']),
    };
}

