/* tslint:disable */
/* eslint-disable */
/**
 * Menzili Backend API
 * REST API for Menzili platform with OTP authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginPost200ResponseData
 */
export interface AuthLoginPost200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost200ResponseData
     */
    otp?: string;
}

/**
 * Check if a given object implements the AuthLoginPost200ResponseData interface.
 */
export function instanceOfAuthLoginPost200ResponseData(value: object): value is AuthLoginPost200ResponseData {
    return true;
}

export function AuthLoginPost200ResponseDataFromJSON(json: any): AuthLoginPost200ResponseData {
    return AuthLoginPost200ResponseDataFromJSONTyped(json, false);
}

export function AuthLoginPost200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginPost200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'otp': json['otp'] == null ? undefined : json['otp'],
    };
}

export function AuthLoginPost200ResponseDataToJSON(json: any): AuthLoginPost200ResponseData {
    return AuthLoginPost200ResponseDataToJSONTyped(json, false);
}

export function AuthLoginPost200ResponseDataToJSONTyped(value?: AuthLoginPost200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'otp': value['otp'],
    };
}

