/* tslint:disable */
/* eslint-disable */
/**
 * Menzili Backend API
 * REST API for Menzili platform with OTP authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthValidOtpPost200ResponseData } from './AuthValidOtpPost200ResponseData';
import {
    AuthValidOtpPost200ResponseDataFromJSON,
    AuthValidOtpPost200ResponseDataFromJSONTyped,
    AuthValidOtpPost200ResponseDataToJSON,
    AuthValidOtpPost200ResponseDataToJSONTyped,
} from './AuthValidOtpPost200ResponseData';

/**
 * 
 * @export
 * @interface AuthValidOtpPost200Response
 */
export interface AuthValidOtpPost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthValidOtpPost200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthValidOtpPost200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthValidOtpPost200Response
     */
    status?: number;
    /**
     * 
     * @type {AuthValidOtpPost200ResponseData}
     * @memberof AuthValidOtpPost200Response
     */
    data?: AuthValidOtpPost200ResponseData;
}

/**
 * Check if a given object implements the AuthValidOtpPost200Response interface.
 */
export function instanceOfAuthValidOtpPost200Response(value: object): value is AuthValidOtpPost200Response {
    return true;
}

export function AuthValidOtpPost200ResponseFromJSON(json: any): AuthValidOtpPost200Response {
    return AuthValidOtpPost200ResponseFromJSONTyped(json, false);
}

export function AuthValidOtpPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthValidOtpPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : AuthValidOtpPost200ResponseDataFromJSON(json['data']),
    };
}

export function AuthValidOtpPost200ResponseToJSON(json: any): AuthValidOtpPost200Response {
    return AuthValidOtpPost200ResponseToJSONTyped(json, false);
}

export function AuthValidOtpPost200ResponseToJSONTyped(value?: AuthValidOtpPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'status': value['status'],
        'data': AuthValidOtpPost200ResponseDataToJSON(value['data']),
    };
}

