/* tslint:disable */
/* eslint-disable */
/**
 * Menzili Backend API
 * REST API for Menzili platform with OTP authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthValidOtpPostRequest
 */
export interface AuthValidOtpPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthValidOtpPostRequest
     */
    phone: string;
    /**
     * 6-digit OTP
     * @type {string}
     * @memberof AuthValidOtpPostRequest
     */
    otpCode: string;
}

/**
 * Check if a given object implements the AuthValidOtpPostRequest interface.
 */
export function instanceOfAuthValidOtpPostRequest(value: object): value is AuthValidOtpPostRequest {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('otpCode' in value) || value['otpCode'] === undefined) return false;
    return true;
}

export function AuthValidOtpPostRequestFromJSON(json: any): AuthValidOtpPostRequest {
    return AuthValidOtpPostRequestFromJSONTyped(json, false);
}

export function AuthValidOtpPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthValidOtpPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'],
        'otpCode': json['otp_code'],
    };
}

export function AuthValidOtpPostRequestToJSON(json: any): AuthValidOtpPostRequest {
    return AuthValidOtpPostRequestToJSONTyped(json, false);
}

export function AuthValidOtpPostRequestToJSONTyped(value?: AuthValidOtpPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
        'otp_code': value['otpCode'],
    };
}

