/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthVerifyOtp200ResponseData
 */
export interface AuthVerifyOtp200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof AuthVerifyOtp200ResponseData
     */
    token: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthVerifyOtp200ResponseData
     */
    fillName: boolean;
}

/**
 * Check if a given object implements the AuthVerifyOtp200ResponseData interface.
 */
export function instanceOfAuthVerifyOtp200ResponseData(value: object): value is AuthVerifyOtp200ResponseData {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('fillName' in value) || value['fillName'] === undefined) return false;
    return true;
}

export function AuthVerifyOtp200ResponseDataFromJSON(json: any): AuthVerifyOtp200ResponseData {
    return AuthVerifyOtp200ResponseDataFromJSONTyped(json, false);
}

export function AuthVerifyOtp200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthVerifyOtp200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'fillName': json['fill_name'],
    };
}

export function AuthVerifyOtp200ResponseDataToJSON(json: any): AuthVerifyOtp200ResponseData {
    return AuthVerifyOtp200ResponseDataToJSONTyped(json, false);
}

export function AuthVerifyOtp200ResponseDataToJSONTyped(value?: AuthVerifyOtp200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'fill_name': value['fillName'],
    };
}

