/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryResource
 */
export interface CategoryResource {
    /**
     * 
     * @type {number}
     * @memberof CategoryResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryResource
     */
    name: string;
    /**
     * dynamic from accessor
     * 'icon' => $this->icon,
     * @type {string}
     * @memberof CategoryResource
     */
    iconPath: string | null;
}

/**
 * Check if a given object implements the CategoryResource interface.
 */
export function instanceOfCategoryResource(value: object): value is CategoryResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('iconPath' in value) || value['iconPath'] === undefined) return false;
    return true;
}

export function CategoryResourceFromJSON(json: any): CategoryResource {
    return CategoryResourceFromJSONTyped(json, false);
}

export function CategoryResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'iconPath': json['icon_path'],
    };
}

export function CategoryResourceToJSON(json: any): CategoryResource {
    return CategoryResourceToJSONTyped(json, false);
}

export function CategoryResourceToJSONTyped(value?: CategoryResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'icon_path': value['iconPath'],
    };
}

