/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CountryResource } from './CountryResource';
import {
    CountryResourceFromJSON,
    CountryResourceFromJSONTyped,
    CountryResourceToJSON,
    CountryResourceToJSONTyped,
} from './CountryResource';
import type { WilayaResource } from './WilayaResource';
import {
    WilayaResourceFromJSON,
    WilayaResourceFromJSONTyped,
    WilayaResourceToJSON,
    WilayaResourceToJSONTyped,
} from './WilayaResource';

/**
 * 
 * @export
 * @interface CityResource
 */
export interface CityResource {
    /**
     * 
     * @type {number}
     * @memberof CityResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CityResource
     */
    name: string;
    /**
     * dynamic from accessor
     * @type {string}
     * @memberof CityResource
     */
    code: string;
    /**
     * 
     * @type {CountryResource}
     * @memberof CityResource
     */
    country?: CountryResource;
    /**
     * 
     * @type {WilayaResource}
     * @memberof CityResource
     */
    wilaya?: WilayaResource;
}

/**
 * Check if a given object implements the CityResource interface.
 */
export function instanceOfCityResource(value: object): value is CityResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function CityResourceFromJSON(json: any): CityResource {
    return CityResourceFromJSONTyped(json, false);
}

export function CityResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'country': json['country'] == null ? undefined : CountryResourceFromJSON(json['country']),
        'wilaya': json['wilaya'] == null ? undefined : WilayaResourceFromJSON(json['wilaya']),
    };
}

export function CityResourceToJSON(json: any): CityResource {
    return CityResourceToJSONTyped(json, false);
}

export function CityResourceToJSONTyped(value?: CityResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'country': CountryResourceToJSON(value['country']),
        'wilaya': WilayaResourceToJSON(value['wilaya']),
    };
}

