/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CountryResource
 */
export interface CountryResource {
    /**
     * 
     * @type {number}
     * @memberof CountryResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CountryResource
     */
    name: string;
    /**
     * dynamic from accessor
     * @type {string}
     * @memberof CountryResource
     */
    code: string | null;
    /**
     * 
     * @type {string}
     * @memberof CountryResource
     */
    flag: string | null;
}

/**
 * Check if a given object implements the CountryResource interface.
 */
export function instanceOfCountryResource(value: object): value is CountryResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('flag' in value) || value['flag'] === undefined) return false;
    return true;
}

export function CountryResourceFromJSON(json: any): CountryResource {
    return CountryResourceFromJSONTyped(json, false);
}

export function CountryResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountryResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'flag': json['flag'],
    };
}

export function CountryResourceToJSON(json: any): CountryResource {
    return CountryResourceToJSONTyped(json, false);
}

export function CountryResourceToJSONTyped(value?: CountryResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'flag': value['flag'],
    };
}

