/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WilayaResource } from './WilayaResource';
import {
    WilayaResourceFromJSON,
    WilayaResourceFromJSONTyped,
    WilayaResourceToJSON,
    WilayaResourceToJSONTyped,
} from './WilayaResource';

/**
 * 
 * @export
 * @interface DetailsWilayas200ResponseData
 */
export interface DetailsWilayas200ResponseData {
    /**
     * 
     * @type {Array<WilayaResource>}
     * @memberof DetailsWilayas200ResponseData
     */
    wilayas: Array<WilayaResource>;
}

/**
 * Check if a given object implements the DetailsWilayas200ResponseData interface.
 */
export function instanceOfDetailsWilayas200ResponseData(value: object): value is DetailsWilayas200ResponseData {
    if (!('wilayas' in value) || value['wilayas'] === undefined) return false;
    return true;
}

export function DetailsWilayas200ResponseDataFromJSON(json: any): DetailsWilayas200ResponseData {
    return DetailsWilayas200ResponseDataFromJSONTyped(json, false);
}

export function DetailsWilayas200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailsWilayas200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'wilayas': ((json['wilayas'] as Array<any>).map(WilayaResourceFromJSON)),
    };
}

export function DetailsWilayas200ResponseDataToJSON(json: any): DetailsWilayas200ResponseData {
    return DetailsWilayas200ResponseDataToJSONTyped(json, false);
}

export function DetailsWilayas200ResponseDataToJSONTyped(value?: DetailsWilayas200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wilayas': ((value['wilayas'] as Array<any>).map(WilayaResourceToJSON)),
    };
}

