/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeatureResource } from './FeatureResource';
import {
    FeatureResourceFromJSON,
    FeatureResourceFromJSONTyped,
    FeatureResourceToJSON,
    FeatureResourceToJSONTyped,
} from './FeatureResource';
import type { NearPlaceResource } from './NearPlaceResource';
import {
    NearPlaceResourceFromJSON,
    NearPlaceResourceFromJSONTyped,
    NearPlaceResourceToJSON,
    NearPlaceResourceToJSONTyped,
} from './NearPlaceResource';
import type { TypeResource } from './TypeResource';
import {
    TypeResourceFromJSON,
    TypeResourceFromJSONTyped,
    TypeResourceToJSON,
    TypeResourceToJSONTyped,
} from './TypeResource';
import type { RentDurationResource } from './RentDurationResource';
import {
    RentDurationResourceFromJSON,
    RentDurationResourceFromJSONTyped,
    RentDurationResourceToJSON,
    RentDurationResourceToJSONTyped,
} from './RentDurationResource';
import type { CategoryResource } from './CategoryResource';
import {
    CategoryResourceFromJSON,
    CategoryResourceFromJSONTyped,
    CategoryResourceToJSON,
    CategoryResourceToJSONTyped,
} from './CategoryResource';

/**
 * 
 * @export
 * @interface DetailsIndex200ResponseData
 */
export interface DetailsIndex200ResponseData {
    /**
     * 
     * @type {Array<FeatureResource>}
     * @memberof DetailsIndex200ResponseData
     */
    features: Array<FeatureResource>;
    /**
     * 
     * @type {Array<CategoryResource>}
     * @memberof DetailsIndex200ResponseData
     */
    categories: Array<CategoryResource>;
    /**
     * 
     * @type {Array<NearPlaceResource>}
     * @memberof DetailsIndex200ResponseData
     */
    nearPlaces: Array<NearPlaceResource>;
    /**
     * 
     * @type {Array<TypeResource>}
     * @memberof DetailsIndex200ResponseData
     */
    types: Array<TypeResource>;
    /**
     * 
     * @type {Array<RentDurationResource>}
     * @memberof DetailsIndex200ResponseData
     */
    rentDurations: Array<RentDurationResource>;
}

/**
 * Check if a given object implements the DetailsIndex200ResponseData interface.
 */
export function instanceOfDetailsIndex200ResponseData(value: object): value is DetailsIndex200ResponseData {
    if (!('features' in value) || value['features'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('nearPlaces' in value) || value['nearPlaces'] === undefined) return false;
    if (!('types' in value) || value['types'] === undefined) return false;
    if (!('rentDurations' in value) || value['rentDurations'] === undefined) return false;
    return true;
}

export function DetailsIndex200ResponseDataFromJSON(json: any): DetailsIndex200ResponseData {
    return DetailsIndex200ResponseDataFromJSONTyped(json, false);
}

export function DetailsIndex200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailsIndex200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'features': ((json['features'] as Array<any>).map(FeatureResourceFromJSON)),
        'categories': ((json['categories'] as Array<any>).map(CategoryResourceFromJSON)),
        'nearPlaces': ((json['near_places'] as Array<any>).map(NearPlaceResourceFromJSON)),
        'types': ((json['types'] as Array<any>).map(TypeResourceFromJSON)),
        'rentDurations': ((json['rent_durations'] as Array<any>).map(RentDurationResourceFromJSON)),
    };
}

export function DetailsIndex200ResponseDataToJSON(json: any): DetailsIndex200ResponseData {
    return DetailsIndex200ResponseDataToJSONTyped(json, false);
}

export function DetailsIndex200ResponseDataToJSONTyped(value?: DetailsIndex200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'features': ((value['features'] as Array<any>).map(FeatureResourceToJSON)),
        'categories': ((value['categories'] as Array<any>).map(CategoryResourceToJSON)),
        'near_places': ((value['nearPlaces'] as Array<any>).map(NearPlaceResourceToJSON)),
        'types': ((value['types'] as Array<any>).map(TypeResourceToJSON)),
        'rent_durations': ((value['rentDurations'] as Array<any>).map(RentDurationResourceToJSON)),
    };
}

