/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailsIndex200ResponseData } from './DetailsIndex200ResponseData';
import {
    DetailsIndex200ResponseDataFromJSON,
    DetailsIndex200ResponseDataFromJSONTyped,
    DetailsIndex200ResponseDataToJSON,
    DetailsIndex200ResponseDataToJSONTyped,
} from './DetailsIndex200ResponseData';

/**
 * 
 * @export
 * @interface DetailsIndex200Response
 */
export interface DetailsIndex200Response {
    /**
     * 
     * @type {boolean}
     * @memberof DetailsIndex200Response
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof DetailsIndex200Response
     */
    message: string;
    /**
     * 
     * @type {DetailsIndex200ResponseData}
     * @memberof DetailsIndex200Response
     */
    data: DetailsIndex200ResponseData;
}

/**
 * Check if a given object implements the DetailsIndex200Response interface.
 */
export function instanceOfDetailsIndex200Response(value: object): value is DetailsIndex200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DetailsIndex200ResponseFromJSON(json: any): DetailsIndex200Response {
    return DetailsIndex200ResponseFromJSONTyped(json, false);
}

export function DetailsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'data': DetailsIndex200ResponseDataFromJSON(json['data']),
    };
}

export function DetailsIndex200ResponseToJSON(json: any): DetailsIndex200Response {
    return DetailsIndex200ResponseToJSONTyped(json, false);
}

export function DetailsIndex200ResponseToJSONTyped(value?: DetailsIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': DetailsIndex200ResponseDataToJSON(value['data']),
    };
}

