/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailsWilayas200ResponseData } from './DetailsWilayas200ResponseData';
import {
    DetailsWilayas200ResponseDataFromJSON,
    DetailsWilayas200ResponseDataFromJSONTyped,
    DetailsWilayas200ResponseDataToJSON,
    DetailsWilayas200ResponseDataToJSONTyped,
} from './DetailsWilayas200ResponseData';

/**
 * 
 * @export
 * @interface DetailsWilayas200Response
 */
export interface DetailsWilayas200Response {
    /**
     * 
     * @type {boolean}
     * @memberof DetailsWilayas200Response
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof DetailsWilayas200Response
     */
    message: string;
    /**
     * 
     * @type {DetailsWilayas200ResponseData}
     * @memberof DetailsWilayas200Response
     */
    data: DetailsWilayas200ResponseData;
}

/**
 * Check if a given object implements the DetailsWilayas200Response interface.
 */
export function instanceOfDetailsWilayas200Response(value: object): value is DetailsWilayas200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DetailsWilayas200ResponseFromJSON(json: any): DetailsWilayas200Response {
    return DetailsWilayas200ResponseFromJSONTyped(json, false);
}

export function DetailsWilayas200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailsWilayas200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'data': DetailsWilayas200ResponseDataFromJSON(json['data']),
    };
}

export function DetailsWilayas200ResponseToJSON(json: any): DetailsWilayas200Response {
    return DetailsWilayas200ResponseToJSONTyped(json, false);
}

export function DetailsWilayas200ResponseToJSONTyped(value?: DetailsWilayas200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': DetailsWilayas200ResponseDataToJSON(value['data']),
    };
}

