/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CityResource } from './CityResource';
import {
    CityResourceFromJSON,
    CityResourceFromJSONTyped,
    CityResourceToJSON,
    CityResourceToJSONTyped,
} from './CityResource';

/**
 * 
 * @export
 * @interface DetailsCities200ResponseData
 */
export interface DetailsCities200ResponseData {
    /**
     * 
     * @type {Array<CityResource>}
     * @memberof DetailsCities200ResponseData
     */
    cities: Array<CityResource>;
}

/**
 * Check if a given object implements the DetailsCities200ResponseData interface.
 */
export function instanceOfDetailsCities200ResponseData(value: object): value is DetailsCities200ResponseData {
    if (!('cities' in value) || value['cities'] === undefined) return false;
    return true;
}

export function DetailsCities200ResponseDataFromJSON(json: any): DetailsCities200ResponseData {
    return DetailsCities200ResponseDataFromJSONTyped(json, false);
}

export function DetailsCities200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailsCities200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'cities': ((json['cities'] as Array<any>).map(CityResourceFromJSON)),
    };
}

export function DetailsCities200ResponseDataToJSON(json: any): DetailsCities200ResponseData {
    return DetailsCities200ResponseDataToJSONTyped(json, false);
}

export function DetailsCities200ResponseDataToJSONTyped(value?: DetailsCities200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cities': ((value['cities'] as Array<any>).map(CityResourceToJSON)),
    };
}

