/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailsCities200ResponseData } from './DetailsCities200ResponseData';
import {
    DetailsCities200ResponseDataFromJSON,
    DetailsCities200ResponseDataFromJSONTyped,
    DetailsCities200ResponseDataToJSON,
    DetailsCities200ResponseDataToJSONTyped,
} from './DetailsCities200ResponseData';

/**
 * 
 * @export
 * @interface DetailsCities200Response
 */
export interface DetailsCities200Response {
    /**
     * 
     * @type {boolean}
     * @memberof DetailsCities200Response
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof DetailsCities200Response
     */
    message: string;
    /**
     * 
     * @type {DetailsCities200ResponseData}
     * @memberof DetailsCities200Response
     */
    data: DetailsCities200ResponseData;
}

/**
 * Check if a given object implements the DetailsCities200Response interface.
 */
export function instanceOfDetailsCities200Response(value: object): value is DetailsCities200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DetailsCities200ResponseFromJSON(json: any): DetailsCities200Response {
    return DetailsCities200ResponseFromJSONTyped(json, false);
}

export function DetailsCities200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailsCities200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'data': DetailsCities200ResponseDataFromJSON(json['data']),
    };
}

export function DetailsCities200ResponseToJSON(json: any): DetailsCities200Response {
    return DetailsCities200ResponseToJSONTyped(json, false);
}

export function DetailsCities200ResponseToJSONTyped(value?: DetailsCities200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': DetailsCities200ResponseDataToJSON(value['data']),
    };
}

