/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureResource
 */
export interface FeatureResource {
    /**
     * 
     * @type {number}
     * @memberof FeatureResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof FeatureResource
     */
    name: string;
    /**
     * dynamic from accessor
     * 'icon' => $this->icon,
     * @type {string}
     * @memberof FeatureResource
     */
    iconPath: string | null;
}

/**
 * Check if a given object implements the FeatureResource interface.
 */
export function instanceOfFeatureResource(value: object): value is FeatureResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('iconPath' in value) || value['iconPath'] === undefined) return false;
    return true;
}

export function FeatureResourceFromJSON(json: any): FeatureResource {
    return FeatureResourceFromJSONTyped(json, false);
}

export function FeatureResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'iconPath': json['icon_path'],
    };
}

export function FeatureResourceToJSON(json: any): FeatureResource {
    return FeatureResourceToJSONTyped(json, false);
}

export function FeatureResourceToJSONTyped(value?: FeatureResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'icon_path': value['iconPath'],
    };
}

