/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImagesResource
 */
export interface ImagesResource {
    /**
     * 
     * @type {string}
     * @memberof ImagesResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ImagesResource
     */
    image: string;
}

/**
 * Check if a given object implements the ImagesResource interface.
 */
export function instanceOfImagesResource(value: object): value is ImagesResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function ImagesResourceFromJSON(json: any): ImagesResource {
    return ImagesResourceFromJSONTyped(json, false);
}

export function ImagesResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagesResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'image': json['image'],
    };
}

export function ImagesResourceToJSON(json: any): ImagesResource {
    return ImagesResourceToJSONTyped(json, false);
}

export function ImagesResourceToJSONTyped(value?: ImagesResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'image': value['image'],
    };
}

