/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListingsUpdatePost200Response
 */
export interface ListingsUpdatePost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListingsUpdatePost200Response
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListingsUpdatePost200Response
     */
    message: string;
}

/**
 * Check if a given object implements the ListingsUpdatePost200Response interface.
 */
export function instanceOfListingsUpdatePost200Response(value: object): value is ListingsUpdatePost200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ListingsUpdatePost200ResponseFromJSON(json: any): ListingsUpdatePost200Response {
    return ListingsUpdatePost200ResponseFromJSONTyped(json, false);
}

export function ListingsUpdatePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingsUpdatePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
    };
}

export function ListingsUpdatePost200ResponseToJSON(json: any): ListingsUpdatePost200Response {
    return ListingsUpdatePost200ResponseToJSONTyped(json, false);
}

export function ListingsUpdatePost200ResponseToJSONTyped(value?: ListingsUpdatePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

