/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginateResource } from './PaginateResource';
import {
    PaginateResourceFromJSON,
    PaginateResourceFromJSONTyped,
    PaginateResourceToJSON,
    PaginateResourceToJSONTyped,
} from './PaginateResource';

/**
 * 
 * @export
 * @interface ListingsIndex200Response
 */
export interface ListingsIndex200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListingsIndex200Response
     */
    success: boolean;
    /**
     * 
     * @type {PaginateResource}
     * @memberof ListingsIndex200Response
     */
    data: PaginateResource;
}

/**
 * Check if a given object implements the ListingsIndex200Response interface.
 */
export function instanceOfListingsIndex200Response(value: object): value is ListingsIndex200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListingsIndex200ResponseFromJSON(json: any): ListingsIndex200Response {
    return ListingsIndex200ResponseFromJSONTyped(json, false);
}

export function ListingsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': PaginateResourceFromJSON(json['data']),
    };
}

export function ListingsIndex200ResponseToJSON(json: any): ListingsIndex200Response {
    return ListingsIndex200ResponseToJSONTyped(json, false);
}

export function ListingsIndex200ResponseToJSONTyped(value?: ListingsIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PaginateResourceToJSON(value['data']),
    };
}

