/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';

/**
 * 
 * @export
 * @interface ListingsDestroy200Response
 */
export interface ListingsDestroy200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListingsDestroy200Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof ListingsDestroy200Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
}

/**
 * Check if a given object implements the ListingsDestroy200Response interface.
 */
export function instanceOfListingsDestroy200Response(value: object): value is ListingsDestroy200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ListingsDestroy200ResponseFromJSON(json: any): ListingsDestroy200Response {
    return ListingsDestroy200ResponseFromJSONTyped(json, false);
}

export function ListingsDestroy200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingsDestroy200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
    };
}

export function ListingsDestroy200ResponseToJSON(json: any): ListingsDestroy200Response {
    return ListingsDestroy200ResponseToJSONTyped(json, false);
}

export function ListingsDestroy200ResponseToJSONTyped(value?: ListingsDestroy200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
    };
}

