/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListingsUpdatePostRequest
 */
export interface ListingsUpdatePostRequest {
    /**
     * 
     * @type {number}
     * @memberof ListingsUpdatePostRequest
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ListingsUpdatePostRequest
     */
    url: string;
}

/**
 * Check if a given object implements the ListingsUpdatePostRequest interface.
 */
export function instanceOfListingsUpdatePostRequest(value: object): value is ListingsUpdatePostRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ListingsUpdatePostRequestFromJSON(json: any): ListingsUpdatePostRequest {
    return ListingsUpdatePostRequestFromJSONTyped(json, false);
}

export function ListingsUpdatePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingsUpdatePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
    };
}

export function ListingsUpdatePostRequestToJSON(json: any): ListingsUpdatePostRequest {
    return ListingsUpdatePostRequestToJSONTyped(json, false);
}

export function ListingsUpdatePostRequestToJSONTyped(value?: ListingsUpdatePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
    };
}

