/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationResource
 */
export interface LocationResource {
    /**
     * 
     * @type {number}
     * @memberof LocationResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LocationResource
     */
    latitude: string;
    /**
     * 
     * @type {string}
     * @memberof LocationResource
     */
    longitude: string;
    /**
     * 
     * @type {string}
     * @memberof LocationResource
     */
    zipCode: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationResource
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof LocationResource
     */
    wilaya: string;
    /**
     * 
     * @type {string}
     * @memberof LocationResource
     */
    wilayaCode: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationResource
     */
    country: string;
}

/**
 * Check if a given object implements the LocationResource interface.
 */
export function instanceOfLocationResource(value: object): value is LocationResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('zipCode' in value) || value['zipCode'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('wilaya' in value) || value['wilaya'] === undefined) return false;
    if (!('wilayaCode' in value) || value['wilayaCode'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    return true;
}

export function LocationResourceFromJSON(json: any): LocationResource {
    return LocationResourceFromJSONTyped(json, false);
}

export function LocationResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'zipCode': json['zip_code'],
        'city': json['city'],
        'wilaya': json['wilaya'],
        'wilayaCode': json['Wilaya_code'],
        'country': json['country'],
    };
}

export function LocationResourceToJSON(json: any): LocationResource {
    return LocationResourceToJSONTyped(json, false);
}

export function LocationResourceToJSONTyped(value?: LocationResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'zip_code': value['zipCode'],
        'city': value['city'],
        'wilaya': value['wilaya'],
        'Wilaya_code': value['wilayaCode'],
        'country': value['country'],
    };
}

