/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemberResource
 */
export interface MemberResource {
    /**
     * 
     * @type {number}
     * @memberof MemberResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MemberResource
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof MemberResource
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof MemberResource
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof MemberResource
     */
    profileImage: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MemberResource
     */
    memberVerified: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberResource
     */
    agentVerified: boolean;
}

/**
 * Check if a given object implements the MemberResource interface.
 */
export function instanceOfMemberResource(value: object): value is MemberResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('profileImage' in value) || value['profileImage'] === undefined) return false;
    if (!('memberVerified' in value) || value['memberVerified'] === undefined) return false;
    if (!('agentVerified' in value) || value['agentVerified'] === undefined) return false;
    return true;
}

export function MemberResourceFromJSON(json: any): MemberResource {
    return MemberResourceFromJSONTyped(json, false);
}

export function MemberResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'email': json['email'],
        'phone': json['phone'],
        'profileImage': json['profile_image'],
        'memberVerified': json['member_verified'],
        'agentVerified': json['agent_verified'],
    };
}

export function MemberResourceToJSON(json: any): MemberResource {
    return MemberResourceToJSONTyped(json, false);
}

export function MemberResourceToJSONTyped(value?: MemberResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
        'profile_image': value['profileImage'],
        'member_verified': value['memberVerified'],
        'agent_verified': value['agentVerified'],
    };
}

