/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NearPlaceResource
 */
export interface NearPlaceResource {
    /**
     * 
     * @type {number}
     * @memberof NearPlaceResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof NearPlaceResource
     */
    name: string;
    /**
     * dynamic from accessor
     * 'icon' => $this->icon,
     * @type {string}
     * @memberof NearPlaceResource
     */
    iconPath: string | null;
}

/**
 * Check if a given object implements the NearPlaceResource interface.
 */
export function instanceOfNearPlaceResource(value: object): value is NearPlaceResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('iconPath' in value) || value['iconPath'] === undefined) return false;
    return true;
}

export function NearPlaceResourceFromJSON(json: any): NearPlaceResource {
    return NearPlaceResourceFromJSONTyped(json, false);
}

export function NearPlaceResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NearPlaceResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'iconPath': json['icon_path'],
    };
}

export function NearPlaceResourceToJSON(json: any): NearPlaceResource {
    return NearPlaceResourceToJSONTyped(json, false);
}

export function NearPlaceResourceToJSONTyped(value?: NearPlaceResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'icon_path': value['iconPath'],
    };
}

