/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginateResourcePagination } from './PaginateResourcePagination';
import {
    PaginateResourcePaginationFromJSON,
    PaginateResourcePaginationFromJSONTyped,
    PaginateResourcePaginationToJSON,
    PaginateResourcePaginationToJSONTyped,
} from './PaginateResourcePagination';
import type { ListingResource } from './ListingResource';
import {
    ListingResourceFromJSON,
    ListingResourceFromJSONTyped,
    ListingResourceToJSON,
    ListingResourceToJSONTyped,
} from './ListingResource';

/**
 * 
 * @export
 * @interface PaginateResource
 */
export interface PaginateResource {
    /**
     * 
     * @type {Array<ListingResource>}
     * @memberof PaginateResource
     */
    listing: Array<ListingResource>;
    /**
     * 
     * @type {PaginateResourcePagination}
     * @memberof PaginateResource
     */
    pagination: PaginateResourcePagination;
}

/**
 * Check if a given object implements the PaginateResource interface.
 */
export function instanceOfPaginateResource(value: object): value is PaginateResource {
    if (!('listing' in value) || value['listing'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginateResourceFromJSON(json: any): PaginateResource {
    return PaginateResourceFromJSONTyped(json, false);
}

export function PaginateResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginateResource {
    if (json == null) {
        return json;
    }
    return {
        
        'listing': ((json['listing'] as Array<any>).map(ListingResourceFromJSON)),
        'pagination': PaginateResourcePaginationFromJSON(json['pagination']),
    };
}

export function PaginateResourceToJSON(json: any): PaginateResource {
    return PaginateResourceToJSONTyped(json, false);
}

export function PaginateResourceToJSONTyped(value?: PaginateResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listing': ((value['listing'] as Array<any>).map(ListingResourceToJSON)),
        'pagination': PaginateResourcePaginationToJSON(value['pagination']),
    };
}

