/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginateResourcePagination
 */
export interface PaginateResourcePagination {
    /**
     * basic info
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    total: string;
    /**
     * 
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    count: string;
    /**
     * 
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    perPage: string;
    /**
     * 
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    currentPage: string;
    /**
     * 
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    totalPages: string;
    /**
     * navigation
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    hasPages: string;
    /**
     * 
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    hasMorePages: string;
    /**
     * page URLs (very useful for frontend)
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    firstPageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    lastPageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    nextPageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    prevPageUrl: string;
    /**
     * index positions
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    to: string;
    /**
     * query meta
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof PaginateResourcePagination
     */
    currentPageUrl: string;
}

/**
 * Check if a given object implements the PaginateResourcePagination interface.
 */
export function instanceOfPaginateResourcePagination(value: object): value is PaginateResourcePagination {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('perPage' in value) || value['perPage'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('hasPages' in value) || value['hasPages'] === undefined) return false;
    if (!('hasMorePages' in value) || value['hasMorePages'] === undefined) return false;
    if (!('firstPageUrl' in value) || value['firstPageUrl'] === undefined) return false;
    if (!('lastPageUrl' in value) || value['lastPageUrl'] === undefined) return false;
    if (!('nextPageUrl' in value) || value['nextPageUrl'] === undefined) return false;
    if (!('prevPageUrl' in value) || value['prevPageUrl'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('currentPageUrl' in value) || value['currentPageUrl'] === undefined) return false;
    return true;
}

export function PaginateResourcePaginationFromJSON(json: any): PaginateResourcePagination {
    return PaginateResourcePaginationFromJSONTyped(json, false);
}

export function PaginateResourcePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginateResourcePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'count': json['count'],
        'perPage': json['per_page'],
        'currentPage': json['current_page'],
        'totalPages': json['total_pages'],
        'hasPages': json['has_pages'],
        'hasMorePages': json['has_more_pages'],
        'firstPageUrl': json['first_page_url'],
        'lastPageUrl': json['last_page_url'],
        'nextPageUrl': json['next_page_url'],
        'prevPageUrl': json['prev_page_url'],
        'from': json['from'],
        'to': json['to'],
        'path': json['path'],
        'currentPageUrl': json['current_page_url'],
    };
}

export function PaginateResourcePaginationToJSON(json: any): PaginateResourcePagination {
    return PaginateResourcePaginationToJSONTyped(json, false);
}

export function PaginateResourcePaginationToJSONTyped(value?: PaginateResourcePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'count': value['count'],
        'per_page': value['perPage'],
        'current_page': value['currentPage'],
        'total_pages': value['totalPages'],
        'has_pages': value['hasPages'],
        'has_more_pages': value['hasMorePages'],
        'first_page_url': value['firstPageUrl'],
        'last_page_url': value['lastPageUrl'],
        'next_page_url': value['nextPageUrl'],
        'prev_page_url': value['prevPageUrl'],
        'from': value['from'],
        'to': value['to'],
        'path': value['path'],
        'current_page_url': value['currentPageUrl'],
    };
}

