/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RentDurationResource
 */
export interface RentDurationResource {
    /**
     * 
     * @type {number}
     * @memberof RentDurationResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof RentDurationResource
     */
    name: string;
}

/**
 * Check if a given object implements the RentDurationResource interface.
 */
export function instanceOfRentDurationResource(value: object): value is RentDurationResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RentDurationResourceFromJSON(json: any): RentDurationResource {
    return RentDurationResourceFromJSONTyped(json, false);
}

export function RentDurationResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentDurationResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function RentDurationResourceToJSON(json: any): RentDurationResource {
    return RentDurationResourceToJSONTyped(json, false);
}

export function RentDurationResourceToJSONTyped(value?: RentDurationResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

