/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * location
 * @export
 * @interface StoreRequestLocation
 */
export interface StoreRequestLocation {
    /**
     * 
     * @type {number}
     * @memberof StoreRequestLocation
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof StoreRequestLocation
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof StoreRequestLocation
     */
    altitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StoreRequestLocation
     */
    zipCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StoreRequestLocation
     */
    cityId: number;
}

/**
 * Check if a given object implements the StoreRequestLocation interface.
 */
export function instanceOfStoreRequestLocation(value: object): value is StoreRequestLocation {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('cityId' in value) || value['cityId'] === undefined) return false;
    return true;
}

export function StoreRequestLocationFromJSON(json: any): StoreRequestLocation {
    return StoreRequestLocationFromJSONTyped(json, false);
}

export function StoreRequestLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreRequestLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'altitude': json['altitude'] == null ? undefined : json['altitude'],
        'zipCode': json['zip_code'] == null ? undefined : json['zip_code'],
        'cityId': json['city_id'],
    };
}

export function StoreRequestLocationToJSON(json: any): StoreRequestLocation {
    return StoreRequestLocationToJSONTyped(json, false);
}

export function StoreRequestLocationToJSONTyped(value?: StoreRequestLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'altitude': value['altitude'],
        'zip_code': value['zipCode'],
        'city_id': value['cityId'],
    };
}

