/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoreRequestLocation } from './StoreRequestLocation';
import {
    StoreRequestLocationFromJSON,
    StoreRequestLocationFromJSONTyped,
    StoreRequestLocationToJSON,
    StoreRequestLocationToJSONTyped,
} from './StoreRequestLocation';

/**
 * 
 * @export
 * @interface StoreRequest
 */
export interface StoreRequest {
    /**
     * 
     * @type {string}
     * @memberof StoreRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof StoreRequest
     */
    description?: string | null;
    /**
     * Price & Property Info
     * @type {number}
     * @memberof StoreRequest
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof StoreRequest
     */
    floor?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoreRequest
     */
    surface: number;
    /**
     * 
     * @type {number}
     * @memberof StoreRequest
     */
    boostLevel?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoreRequest
     */
    minDuration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoreRequest
     */
    numberRooms?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoreRequest
     */
    numberPersons?: number | null;
    /**
     * Booleans
     * @type {boolean}
     * @memberof StoreRequest
     */
    isReady?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StoreRequest
     */
    isNegotiable?: boolean;
    /**
     * Enum
     * 'moderation_status' => [
     * 'sometimes',
     * Rule::in(['pending', 'approved', 'rejected'])
     * ],
     * Image
     * @type {Blob}
     * @memberof StoreRequest
     */
    mainImage: Blob;
    /**
     * Foreign Keys
     * @type {number}
     * @memberof StoreRequest
     */
    memberId: number;
    /**
     * 
     * @type {number}
     * @memberof StoreRequest
     */
    rentDurationId: number;
    /**
     * 
     * @type {number}
     * @memberof StoreRequest
     */
    typeId: number;
    /**
     * 
     * @type {StoreRequestLocation}
     * @memberof StoreRequest
     */
    location: StoreRequestLocation;
    /**
     * Many to Many
     * @type {Array<number>}
     * @memberof StoreRequest
     */
    categories?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof StoreRequest
     */
    features?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof StoreRequest
     */
    nearPlaces?: Array<number> | null;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof StoreRequest
     */
    images?: Array<Blob> | null;
}

/**
 * Check if a given object implements the StoreRequest interface.
 */
export function instanceOfStoreRequest(value: object): value is StoreRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('surface' in value) || value['surface'] === undefined) return false;
    if (!('mainImage' in value) || value['mainImage'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('rentDurationId' in value) || value['rentDurationId'] === undefined) return false;
    if (!('typeId' in value) || value['typeId'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function StoreRequestFromJSON(json: any): StoreRequest {
    return StoreRequestFromJSONTyped(json, false);
}

export function StoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'],
        'floor': json['floor'] == null ? undefined : json['floor'],
        'surface': json['surface'],
        'boostLevel': json['boost_level'] == null ? undefined : json['boost_level'],
        'minDuration': json['min_duration'] == null ? undefined : json['min_duration'],
        'numberRooms': json['number_rooms'] == null ? undefined : json['number_rooms'],
        'numberPersons': json['number_persons'] == null ? undefined : json['number_persons'],
        'isReady': json['is_ready'] == null ? undefined : json['is_ready'],
        'isNegotiable': json['is_negotiable'] == null ? undefined : json['is_negotiable'],
        'mainImage': json['main_image'],
        'memberId': json['member_id'],
        'rentDurationId': json['rent_duration_id'],
        'typeId': json['type_id'],
        'location': StoreRequestLocationFromJSON(json['location']),
        'categories': json['categories'] == null ? undefined : json['categories'],
        'features': json['features'] == null ? undefined : json['features'],
        'nearPlaces': json['near_places'] == null ? undefined : json['near_places'],
        'images': json['images'] == null ? undefined : json['images'],
    };
}

export function StoreRequestToJSON(json: any): StoreRequest {
    return StoreRequestToJSONTyped(json, false);
}

export function StoreRequestToJSONTyped(value?: StoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'price': value['price'],
        'floor': value['floor'],
        'surface': value['surface'],
        'boost_level': value['boostLevel'],
        'min_duration': value['minDuration'],
        'number_rooms': value['numberRooms'],
        'number_persons': value['numberPersons'],
        'is_ready': value['isReady'],
        'is_negotiable': value['isNegotiable'],
        'main_image': value['mainImage'],
        'member_id': value['memberId'],
        'rent_duration_id': value['rentDurationId'],
        'type_id': value['typeId'],
        'location': StoreRequestLocationToJSON(value['location']),
        'categories': value['categories'],
        'features': value['features'],
        'near_places': value['nearPlaces'],
        'images': value['images'],
    };
}

