/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRequestLocation
 */
export interface UpdateRequestLocation {
    /**
     * 
     * @type {number}
     * @memberof UpdateRequestLocation
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateRequestLocation
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateRequestLocation
     */
    cityId?: number;
}

/**
 * Check if a given object implements the UpdateRequestLocation interface.
 */
export function instanceOfUpdateRequestLocation(value: object): value is UpdateRequestLocation {
    return true;
}

export function UpdateRequestLocationFromJSON(json: any): UpdateRequestLocation {
    return UpdateRequestLocationFromJSONTyped(json, false);
}

export function UpdateRequestLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRequestLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'cityId': json['city_id'] == null ? undefined : json['city_id'],
    };
}

export function UpdateRequestLocationToJSON(json: any): UpdateRequestLocation {
    return UpdateRequestLocationToJSONTyped(json, false);
}

export function UpdateRequestLocationToJSONTyped(value?: UpdateRequestLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'city_id': value['cityId'],
    };
}

