/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateRequestLocation } from './UpdateRequestLocation';
import {
    UpdateRequestLocationFromJSON,
    UpdateRequestLocationFromJSONTyped,
    UpdateRequestLocationToJSON,
    UpdateRequestLocationToJSONTyped,
} from './UpdateRequestLocation';

/**
 * 
 * @export
 * @interface UpdateRequest
 */
export interface UpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRequest
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateRequest
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateRequest
     */
    floor?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateRequest
     */
    surface?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateRequest
     */
    boostLevel?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateRequest
     */
    minDuration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateRequest
     */
    numberRooms?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateRequest
     */
    numberPersons?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateRequest
     */
    isReady?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateRequest
     */
    isNegotiable?: boolean;
    /**
     * 
     * @type {Blob}
     * @memberof UpdateRequest
     */
    mainImage?: Blob | null;
    /**
     * 
     * @type {UpdateRequestLocation}
     * @memberof UpdateRequest
     */
    location?: UpdateRequestLocation;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateRequest
     */
    categories?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateRequest
     */
    features?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateRequest
     */
    nearPlaces?: Array<number> | null;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof UpdateRequest
     */
    images?: Array<Blob> | null;
}

/**
 * Check if a given object implements the UpdateRequest interface.
 */
export function instanceOfUpdateRequest(value: object): value is UpdateRequest {
    return true;
}

export function UpdateRequestFromJSON(json: any): UpdateRequest {
    return UpdateRequestFromJSONTyped(json, false);
}

export function UpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'floor': json['floor'] == null ? undefined : json['floor'],
        'surface': json['surface'] == null ? undefined : json['surface'],
        'boostLevel': json['boost_level'] == null ? undefined : json['boost_level'],
        'minDuration': json['min_duration'] == null ? undefined : json['min_duration'],
        'numberRooms': json['number_rooms'] == null ? undefined : json['number_rooms'],
        'numberPersons': json['number_persons'] == null ? undefined : json['number_persons'],
        'isReady': json['is_ready'] == null ? undefined : json['is_ready'],
        'isNegotiable': json['is_negotiable'] == null ? undefined : json['is_negotiable'],
        'mainImage': json['main_image'] == null ? undefined : json['main_image'],
        'location': json['location'] == null ? undefined : UpdateRequestLocationFromJSON(json['location']),
        'categories': json['categories'] == null ? undefined : json['categories'],
        'features': json['features'] == null ? undefined : json['features'],
        'nearPlaces': json['near_places'] == null ? undefined : json['near_places'],
        'images': json['images'] == null ? undefined : json['images'],
    };
}

export function UpdateRequestToJSON(json: any): UpdateRequest {
    return UpdateRequestToJSONTyped(json, false);
}

export function UpdateRequestToJSONTyped(value?: UpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'price': value['price'],
        'floor': value['floor'],
        'surface': value['surface'],
        'boost_level': value['boostLevel'],
        'min_duration': value['minDuration'],
        'number_rooms': value['numberRooms'],
        'number_persons': value['numberPersons'],
        'is_ready': value['isReady'],
        'is_negotiable': value['isNegotiable'],
        'main_image': value['mainImage'],
        'location': UpdateRequestLocationToJSON(value['location']),
        'categories': value['categories'],
        'features': value['features'],
        'near_places': value['nearPlaces'],
        'images': value['images'],
    };
}

