/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email: string | null;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    emailVerifiedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    profileImage: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    otpCode: string | null;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    otpExpiresAt: Date | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    isActive: number;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    phoneVerifiedAt: Date | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    isAdmin: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    deviceToken: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastLoginAt: string | null;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('emailVerifiedAt' in value) || value['emailVerifiedAt'] === undefined) return false;
    if (!('profileImage' in value) || value['profileImage'] === undefined) return false;
    if (!('otpCode' in value) || value['otpCode'] === undefined) return false;
    if (!('otpExpiresAt' in value) || value['otpExpiresAt'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('phoneVerifiedAt' in value) || value['phoneVerifiedAt'] === undefined) return false;
    if (!('isAdmin' in value) || value['isAdmin'] === undefined) return false;
    if (!('deviceToken' in value) || value['deviceToken'] === undefined) return false;
    if (!('lastLoginAt' in value) || value['lastLoginAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'phone': json['phone'],
        'email': json['email'],
        'emailVerifiedAt': (json['email_verified_at'] == null ? null : new Date(json['email_verified_at'])),
        'profileImage': json['profile_image'],
        'otpCode': json['otp_code'],
        'otpExpiresAt': (json['otp_expires_at'] == null ? null : new Date(json['otp_expires_at'])),
        'isActive': json['is_active'],
        'phoneVerifiedAt': (json['phone_verified_at'] == null ? null : new Date(json['phone_verified_at'])),
        'isAdmin': json['is_admin'],
        'deviceToken': json['device_token'],
        'lastLoginAt': json['last_login_at'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'phone': value['phone'],
        'email': value['email'],
        'email_verified_at': value['emailVerifiedAt'] == null ? value['emailVerifiedAt'] : value['emailVerifiedAt'].toISOString(),
        'profile_image': value['profileImage'],
        'otp_code': value['otpCode'],
        'otp_expires_at': value['otpExpiresAt'] == null ? value['otpExpiresAt'] : value['otpExpiresAt'].toISOString(),
        'is_active': value['isActive'],
        'phone_verified_at': value['phoneVerifiedAt'] == null ? value['phoneVerifiedAt'] : value['phoneVerifiedAt'].toISOString(),
        'is_admin': value['isAdmin'],
        'device_token': value['deviceToken'],
        'last_login_at': value['lastLoginAt'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

