/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResource
 */
export interface UserResource {
    /**
     * 
     * @type {number}
     * @memberof UserResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserResource
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResource
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof UserResource
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResource
     */
    profileImage: string | null;
}

/**
 * Check if a given object implements the UserResource interface.
 */
export function instanceOfUserResource(value: object): value is UserResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('profileImage' in value) || value['profileImage'] === undefined) return false;
    return true;
}

export function UserResourceFromJSON(json: any): UserResource {
    return UserResourceFromJSONTyped(json, false);
}

export function UserResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'phone': json['phone'],
        'email': json['email'],
        'profileImage': json['profile_image'],
    };
}

export function UserResourceToJSON(json: any): UserResource {
    return UserResourceToJSONTyped(json, false);
}

export function UserResourceToJSONTyped(value?: UserResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'phone': value['phone'],
        'email': value['email'],
        'profile_image': value['profileImage'],
    };
}

