/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CountryResource } from './CountryResource';
import {
    CountryResourceFromJSON,
    CountryResourceFromJSONTyped,
    CountryResourceToJSON,
    CountryResourceToJSONTyped,
} from './CountryResource';

/**
 * 
 * @export
 * @interface WilayaResource
 */
export interface WilayaResource {
    /**
     * 
     * @type {number}
     * @memberof WilayaResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof WilayaResource
     */
    name: string;
    /**
     * dynamic from accessor
     * @type {string}
     * @memberof WilayaResource
     */
    code: string | null;
    /**
     * 
     * @type {CountryResource}
     * @memberof WilayaResource
     */
    country?: CountryResource;
}

/**
 * Check if a given object implements the WilayaResource interface.
 */
export function instanceOfWilayaResource(value: object): value is WilayaResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function WilayaResourceFromJSON(json: any): WilayaResource {
    return WilayaResourceFromJSONTyped(json, false);
}

export function WilayaResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WilayaResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'country': json['country'] == null ? undefined : CountryResourceFromJSON(json['country']),
    };
}

export function WilayaResourceToJSON(json: any): WilayaResource {
    return WilayaResourceToJSONTyped(json, false);
}

export function WilayaResourceToJSONTyped(value?: WilayaResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'country': CountryResourceToJSON(value['country']),
    };
}

